name: first

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    # can only use branches OR branches-ignore
    # branches-ignore:
    #   - dev
    #   - 'feature/another-branch-to-ignore'

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps: 
    - name: Step one
      uses: actions/checkout@v2
    - name: Step two
      run: "Get-ChildItem Env: | Sort-Object Name"
